version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  build-and-deploy:
    jobs:
      - main

jobs:
  main:
    docker:
      - image: 'cimg/node:current'
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e8:91:89:20:2f:03:d5:98:64:76:5b:2c:f8:16:44:ef"
      - run:
          name: Prepare and install enviroment's package stuff
          command: yarn install
      - run:
          name: Build webapp
          command: yarn build
      - run:
          name: Install gh-pages
          command: sudo npm install -g --silent gh-pages
      - run:
            name: Configurate git
            command: |
              git config --global user.email "zshn@pm.me"
              git config --global user.name "cibuild"
      - run:
          name: Deploy to github pages
          command: gh-pages --dotfiles --message "[skip ci] Build docs" --dist dist